# resource-marathon-deploy task-readme-github-pages.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7.1

inputs:
- name: resource-marathon-deploy

outputs:
- name: resource-marathon-deploy-updated

run:
  path: ./resource-marathon-deploy/ci/scripts/readme-github-pages.sh
