platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7.1

inputs:
- name: resource-marathon-deploy

run:
  path: ./resource-marathon-deploy/ci/scripts/unit-tests.sh